name: CI

permissions:
  contents: read

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          rust-toolchain: manual

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "--no-default-features", "--all-features"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo build
        run: cargo build ${{ matrix.features }}
      - name: Cargo test (all features)
        run: cargo test --all-features
