name: CI

permissions:
  contents: read

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "--no-default-features", "--all-features"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo build
        run: cargo build ${{ matrix.features }}
      - name: Cargo test (all features)
        run: cargo test --all-features
